-- IMPULSO 1.0 · Supabase
-- Ejecutar en SQL Editor del proyecto Supabase.
create table if not exists public.user_data (
  user_id uuid primary key references auth.users(id) on delete cascade,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.user_data enable row level security;

drop policy if exists "user_data_select_own" on public.user_data;
drop policy if exists "user_data_insert_own" on public.user_data;
drop policy if exists "user_data_update_own" on public.user_data;
drop policy if exists "user_data_delete_own" on public.user_data;
create policy "user_data_select_own" on public.user_data for select using (auth.uid() = user_id);
create policy "user_data_insert_own" on public.user_data for insert with check (auth.uid() = user_id);
create policy "user_data_update_own" on public.user_data for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "user_data_delete_own" on public.user_data for delete using (auth.uid() = user_id);

-- Fotos y archivos privados por usuario.
insert into storage.buckets (id,name,public) values ('impulso-files','impulso-files',false)
on conflict (id) do nothing;

drop policy if exists "impulso_files_read_own" on storage.objects;
drop policy if exists "impulso_files_insert_own" on storage.objects;
drop policy if exists "impulso_files_update_own" on storage.objects;
drop policy if exists "impulso_files_delete_own" on storage.objects;
create policy "impulso_files_read_own" on storage.objects for select to authenticated using (bucket_id='impulso-files' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "impulso_files_insert_own" on storage.objects for insert to authenticated with check (bucket_id='impulso-files' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "impulso_files_update_own" on storage.objects for update to authenticated using (bucket_id='impulso-files' and (storage.foldername(name))[1] = auth.uid()::text) with check (bucket_id='impulso-files' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "impulso_files_delete_own" on storage.objects for delete to authenticated using (bucket_id='impulso-files' and (storage.foldername(name))[1] = auth.uid()::text);

-- Índice útil para sincronización y auditoría.
create index if not exists user_data_updated_at_idx on public.user_data(updated_at desc);


-- Push notifications y recordatorios programados
create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  subscription jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.push_subscriptions enable row level security;
drop policy if exists "push_subscriptions_select_own" on public.push_subscriptions;
drop policy if exists "push_subscriptions_insert_own" on public.push_subscriptions;
drop policy if exists "push_subscriptions_update_own" on public.push_subscriptions;
drop policy if exists "push_subscriptions_delete_own" on public.push_subscriptions;
create policy "push_subscriptions_select_own" on public.push_subscriptions for select to authenticated using (auth.uid() = user_id);
create policy "push_subscriptions_insert_own" on public.push_subscriptions for insert to authenticated with check (auth.uid() = user_id);
create policy "push_subscriptions_update_own" on public.push_subscriptions for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "push_subscriptions_delete_own" on public.push_subscriptions for delete to authenticated using (auth.uid() = user_id);

create table if not exists public.scheduled_reminders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  reminder_id text not null,
  title text not null,
  due_at timestamptz not null,
  completed boolean not null default false,
  sent boolean not null default false,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  unique(user_id, reminder_id)
);
alter table public.scheduled_reminders enable row level security;
drop policy if exists "scheduled_reminders_select_own" on public.scheduled_reminders;
drop policy if exists "scheduled_reminders_insert_own" on public.scheduled_reminders;
drop policy if exists "scheduled_reminders_update_own" on public.scheduled_reminders;
drop policy if exists "scheduled_reminders_delete_own" on public.scheduled_reminders;
create policy "scheduled_reminders_select_own" on public.scheduled_reminders for select to authenticated using (auth.uid() = user_id);
create policy "scheduled_reminders_insert_own" on public.scheduled_reminders for insert to authenticated with check (auth.uid() = user_id);
create policy "scheduled_reminders_update_own" on public.scheduled_reminders for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "scheduled_reminders_delete_own" on public.scheduled_reminders for delete to authenticated using (auth.uid() = user_id);
create index if not exists scheduled_reminders_due_idx on public.scheduled_reminders(sent, completed, due_at);

-- Para enviar recordatorios con precisión de 1 minuto, habilitá pg_cron + pg_net y configurá Vault.
-- Reemplazá los valores antes de ejecutar.
-- select vault.create_secret('https://YOUR_PROJECT.supabase.co', 'project_url');
-- select vault.create_secret('YOUR_PUBLISHABLE_KEY', 'publishable_key');
-- select vault.create_secret('YOUR_PUSH_DISPATCH_SECRET', 'push_dispatch_secret');
-- select cron.schedule('impulso-push-dispatch','* * * * *',$$select net.http_post(
--   url := (select decrypted_secret from vault.decrypted_secrets where name='project_url') || '/functions/v1/push-dispatch',
--   headers := jsonb_build_object('Content-Type','application/json','apikey',(select decrypted_secret from vault.decrypted_secrets where name='publishable_key'),'x-dispatch-secret',(select decrypted_secret from vault.decrypted_secrets where name='push_dispatch_secret')),
--   body := '{}'::jsonb
-- )$$);
